spring:
  application:
    name: neo-story
  datasource:
    url: jdbc:h2:file:./db/neo-story
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

app:
  jwt:
    issuer: neo-story-spring-app
    subject: user-details
    secret: best-jwt-secret-ever
    duration: 86400
